title: nyoung note
author: nyoung
email: 08eychoi@gmail.com
url: http://localhost:4000
#url: https://nyoung08.github.io
baseurl: "/"
future: true
# subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
#description: "nyoung note" 
#description of the site (multiple lines allowed)

permalink: pretty
#permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

comments:
  provider: utterances        

utterances:
  repo: "nyoung08/4comment"
  issue-term: "pathname"
  label: "Comments"
  theme: "github-light"


